#!/usr/bin/env bash

# Exit the script if any of the commands fail
set -e
set -u
set -o pipefail

# Set working directory to the location of this script
cd "$(dirname "${BASH_SOURCE[0]}")"
STARTDIR="$(pwd)"
DESTDIR="$STARTDIR/pkg"
OUTDIR="$STARTDIR/deb"
mkdir "$OUTDIR"

# get version
repo="gotson/komga"
api=$(curl -s "https://api.github.com/repos/$repo/releases/latest")
new=$(echo $api | grep -oP '"tag_name": "\K(.*)(?=")')

wget -q https://github.com/$repo/releases/download/$new/komga-$new.jar -O "$STARTDIR/komga.jar"

all_dist=('all')
for dist in "${all_dist[@]}"; do

    # Remove potential leftovers from a previous build
    rm -rf "$DESTDIR"

    # Install files
    install -Dm 755 "$STARTDIR/komga.jar" "$DESTDIR/usr/share/java/komga.jar"
    install -Dm 755 "$STARTDIR/komga.service" "$DESTDIR/etc/systemd/system/komga.service"
    install -dm 750 "$DESTDIR/var/lib/komga"
    
    mkdir -p "$DESTDIR/DEBIAN"
    cp "$STARTDIR/DEBIAN/"* "$DESTDIR/DEBIAN/"
    
    # Modify control file for build
    sed -i "s/VERSION-TO-REPLACE/$new/" "$DESTDIR/DEBIAN/control"
    sed -i "s/ARCHI-TO-REPLACE/$dist/" "$DESTDIR/DEBIAN/control"
    
    # Build .deb
    dpkg-deb --build "$DESTDIR" "$OUTDIR"
    
done