#!/usr/bin/env bash
chown komga: /var/lib/gitea

[ -d  /run/systemd/system/ ] && systemctl daemon-reload
[ -d  /run/systemd/system/ ] && systemctl enable komga
[ -d  /run/systemd/system/ ] && systemctl restart komga

exit 0