name: package

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-debs:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate deb packages
        run: |
          node generate-debs.mjs
      - name: Generate artifact (local only)
        if: ${{ env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: |
            current.txt
            deb/
      - name: Generate release (Github only)
        if: ${{ !env.ACT }}
        run: |
          node generate-release.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}